config/routes.rb
Rails.application.routes.draw do
  root 'store#index'
  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :smartphones
    resources :models
    resources :manufacturers
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
end

app/controllers/admin/manufacturers_controller.rb
class Admin::ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: %i[ show edit update destroy ]

  # GET /manufacturers or /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
  end

  # GET /manufacturers/1 or /manufacturers/1.json
  def show
  end

  # GET /manufacturers/new
  def new
    @manufacturer = Manufacturer.new
  end

  # GET /manufacturers/1/edit
  def edit
  end

  # POST /manufacturers or /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to admin_manufacturer_url(@manufacturer), notice: "Manufacturer was successfully created." }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturers/1 or /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        format.html { redirect_to admin_manufacturer_url(@manufacturer), notice: "Manufacturer was successfully updated." }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1 or /manufacturers/1.json
  def destroy
    @manufacturer.destroy!

    respond_to do |format|
      format.html { redirect_to admin_manufacturers_url, notice: "Manufacturer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manufacturer_params
      params.require(:manufacturer).permit(:name)
    end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/admin/manufacturers/_form.html.erb
<%= form_with(model: manufacturer, url: url) do |form| %>
  <% if manufacturer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
        <% manufacturer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="from-group">
    <%= form.button "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/manufacturers/_manufacturer.html.erb
<div id="<%= dom_id manufacturer %>">
  <p>
    <strong>Name:</strong>
    <%= manufacturer.name %>
  </p>

</div>

app/views/admin/manufacturers/edit.html.erb
<h1>Editing manufacturer</h1>

<%= render "form", manufacturer: @manufacturer, url: admin_manufacturer_path(@manufacturer) %>

<br>

<div>
  <%= link_to "Show this manufacturer", admin_manufacturer_path(@manufacturer) %> |
  <%= link_to "Back to manufacturers", admin_manufacturers_path %>
</div>

app/views/admin/manufacturers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Manufacturers</h1>

<div id="manufacturers">
  <% @manufacturers.each do |manufacturer| %>
    <%= render manufacturer %>
    <p>
      <%= link_to "Show this manufacturer", admin_manufacturer_path(manufacturer) %>
    </p>
  <% end %>
</div>

<%= link_to "New manufacturer", new_admin_manufacturer_path %>

app/views/admin/manufacturers/new.html.erb
<h1>New manufacturer</h1>

<%= render "form", manufacturer: @manufacturer, url: admin_manufacturers_path %>

<br>

<div>
  <%= link_to "Back to manufacturers", admin_manufacturers_path %>
</div>

app/views/admin/manufacturers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @manufacturer %>

<div>
  <%= link_to "Edit this manufacturer", edit_admin_manufacturer_path(@manufacturer) %> |
  <%= link_to "Back to manufacturers", admin_manufacturers_path %>

  <%= button_to "Destroy this manufacturer", admin_manufacturer_path(@manufacturer), method: :delete %>
</div>