config/routes.rb
Rails.application.routes.draw do
  root 'store#index'
  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :smartphones
    resources :models
    resources :manufacturers
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/smartphone.rb
class Smartphone < ApplicationRecord
  belongs_to :manufacturer
  belongs_to :model
end

app/controllers/admin/smartphones_controller.rb
class Admin::SmartphonesController < ApplicationController
  before_action :set_smartphone, only: %i[ show edit update destroy ]

  # GET /smartphones or /smartphones.json
  def index
    @smartphones = Smartphone.all
  end

  # GET /smartphones/1 or /smartphones/1.json
  def show
  end

  # GET /smartphones/new
  def new
    @smartphone = Smartphone.new
  end

  # GET /smartphones/1/edit
  def edit
  end

  # POST /smartphones or /smartphones.json
  def create
    @smartphone = Smartphone.new(smartphone_params)

    respond_to do |format|
      if @smartphone.save
        format.html { redirect_to admin_smartphone_url(@smartphone), notice: "Smartphone was successfully created." }
        format.json { render :show, status: :created, location: @smartphone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smartphones/1 or /smartphones/1.json
  def update
    respond_to do |format|
      if @smartphone.update(smartphone_params)
        format.html { redirect_to admin_smartphone_url(@smartphone), notice: "Smartphone was successfully updated." }
        format.json { render :show, status: :ok, location: @smartphone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smartphones/1 or /smartphones/1.json
  def destroy
    @smartphone.destroy!

    respond_to do |format|
      format.html { redirect_to admin_smartphones_url, notice: "Smartphone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smartphone
      @smartphone = Smartphone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def smartphone_params
      params.require(:smartphone).permit(:manufacturer_id, :model_id, :data_memory, :year_of_manufacture, :os_version, :body_color, :price)
    end
end

app/controllers/smartphones_controller.rb
class SmartphonesController < ApplicationController
  before_action :set_smartphone, only: %i[ show edit update destroy ]

  # GET /smartphones or /smartphones.json
  def index
    @smartphones = Smartphone.all
  end

  # GET /smartphones/1 or /smartphones/1.json
  def show
  end

  # GET /smartphones/new
  def new
    @smartphone = Smartphone.new
  end

  # GET /smartphones/1/edit
  def edit
  end

  # POST /smartphones or /smartphones.json
  def create
    @smartphone = Smartphone.new(smartphone_params)

    respond_to do |format|
      if @smartphone.save
        format.html { redirect_to smartphone_url(@smartphone), notice: "Smartphone was successfully created." }
        format.json { render :show, status: :created, location: @smartphone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smartphones/1 or /smartphones/1.json
  def update
    respond_to do |format|
      if @smartphone.update(smartphone_params)
        format.html { redirect_to smartphone_url(@smartphone), notice: "Smartphone was successfully updated." }
        format.json { render :show, status: :ok, location: @smartphone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smartphones/1 or /smartphones/1.json
  def destroy
    @smartphone.destroy!

    respond_to do |format|
      format.html { redirect_to smartphones_url, notice: "Smartphone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smartphone
      @smartphone = Smartphone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def smartphone_params
      params.require(:smartphone).permit(:manufacturer_id, :model_id, :data_memory, :year_of_manufacture, :os_version, :body_color, :price)
    end
end

app/helpers/smartphones_helper.rb
module SmartphonesHelper
end

app/views/smartphones/_form.html.erb
<%= form_with(model: smartphone) do |form| %>
  <% if smartphone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(smartphone.errors.count, "error") %> prohibited this smartphone from being saved:</h2>

      <ul>
        <% smartphone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 form-group">
    <%= form.label :manufacturer_id, class: "form-label" %>
    <%= form.select :manufacturer_id, Manufacturer.all.collect {|manu| [manu.name, manu.id]}, {prompt: "Select a manufacturer"}, {class: "form-select"} %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :model_id, class: "form-label" %>
    <%= form.select :model_id, Model.all.collect {|m| [m.name, m.id]} , {prompt: "Select a model"}, { class: "form-select" } %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :data_memory, class: "form-label" %>
    <%= form.text_field :data_memory, class: "form-control" %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :year_of_manufacture, class: "form-label" %>
    <%= form.number_field :year_of_manufacture, class: "form-control" %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :os_version, class: "form-label" %>
    <%= form.text_field :os_version, class: "form-control" %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :body_color, class: "form-label" %>
    <%= form.text_field :body_color, class: "form-control" %>
  </div>

  <div class="mb-3 form-group">
    <%= form.label :price, class: "form-label" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="mb-3 form-group">
    <%= form.button "Submit", class: "btn btn-primary" %>
    <%= link_to "Cancel", smartphones_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/smartphones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Smartphones</h1>

<div id="smartphones">
  <% @smartphones.each do |smartphone| %>
    <%= render smartphone %>
    <p>
      <%= link_to "Show this smartphone", smartphone %>
    </p>
  <% end %>
</div>

<%= link_to "New smartphone", new_smartphone_path %>