config/routes.rb
Rails.application.routes.draw do
  root 'store#index'
  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :smartphones
    resources :models
    resources :manufacturers
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
end

app/models/smartphone.rb
class Smartphone < ApplicationRecord
  belongs_to :manufacturer
  belongs_to :model
end

app/controllers/admin/models_controller.rb
class Admin::ModelsController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  # GET /models or /models.json
  def index
    @models = Model.all
  end

  # GET /models/1 or /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models or /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to admin_model_url(@model), notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1 or /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to admin_model_url(@model), notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1 or /models/1.json
  def destroy
    @model.destroy!

    respond_to do |format|
      format.html { redirect_to admin_models_url, notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def model_params
      params.require(:model).permit(:name)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/admin/models/_form.html.erb
<%= form_with(model: model, url: url) do |form| %>
  <% if model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.button "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/models/_model.html.erb
<div id="<%= dom_id model %>">
  <p>
    <strong>Name:</strong>
    <%= model.name %>
  </p>

</div>

app/views/admin/models/edit.html.erb
<h1>Editing model</h1>

<%= render "form", model: @model, url: admin_model_path(@model) %>

<br>

<div>
  <%= link_to "Show this model", edit_admin_model_path(@model) %> |
  <%= link_to "Back to models", admin_models_path %>
</div>

app/views/admin/models/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Models</h1>

<div id="models">
  <% @models.each do |model| %>
    <%= render model %>
    <p>
      <%= link_to "Show this model", admin_model_path(model) %>
    </p>
  <% end %>
</div>

<%= link_to "New model", new_admin_model_path %>

app/views/admin/models/new.html.erb
<h1>New model</h1>

<%= render "form", model: @model, url: admin_models_path %>

<br>

<div>
  <%= link_to "Back to models", admin_models_path %>
</div>

app/views/admin/models/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this model", edit_admin_model_path(@model) %> |
  <%= link_to "Back to models", admin_models_path %>

  <%= button_to "Destroy this model", admin_model_path(@model), method: :delete %>
</div>